[2023-10-12T22:00:12.818+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-10-12T22:00:12.927+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.crawl_data scheduled__2023-10-12T22:00:00+00:00 [queued]>
[2023-10-12T22:00:12.932+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.crawl_data scheduled__2023-10-12T22:00:00+00:00 [queued]>
[2023-10-12T22:00:12.932+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-12T22:00:12.940+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_data> on 2023-10-12 22:00:00+00:00
[2023-10-12T22:00:12.943+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2023-10-12T22:00:12.945+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'crawl_data', 'scheduled__2023-10-12T22:00:00+00:00', '--job-id', '657', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpdgvt414x']
[2023-10-12T22:00:12.946+0000] {standard_task_runner.py:85} INFO - Job 657: Subtask crawl_data
[2023-10-12T22:00:12.954+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-12T22:00:12.977+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL.crawl_data scheduled__2023-10-12T22:00:00+00:00 [running]> on host cba2d0d235e2
[2023-10-12T22:00:12.985+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-10-12T22:00:13.035+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='crawl_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-12T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-12T22:00:00+00:00'
[2023-10-12T22:00:13.040+0000] {base.py:73} INFO - Using connection ID 'Booking' for task execution.
[2023-10-12T22:00:13.200+0000] {logging_mixin.py:151} INFO - link https://www.booking.com/searchresults.vi.html?ss=TP.+H%C3%B4%CC%80+Chi%CC%81+Minh%2C+Vi%C3%AA%CC%A3t+Nam&efdco=1&label=gen173nr-1BCAEoggI46AdIM1gEaPQBiAEBmAEquAEXyAEM2AEB6AEBiAIBqAIDuAL1lMaoBsACAdICJGM1MWM1ODQyLWYzMmMtNGExMi1iMWFmLWM4YzliMDE0MzJlMNgCBeACAQ&sid=a3cf4761bc87283185953cebac7c42a2&aid=304142&lang=vi&sb=1&src_elem=sb&src=index&dest_id=-3730078&dest_type=city&checkin=2024-01-02&checkout=2024-01-03&group_adults=2&no_rooms=1&group_children=0&sb_travel_purpose=leisure&selected_currency=VND&offset={}
[2023-10-12T22:00:15.145+0000] {logging_mixin.py:151} INFO - link https://www.booking.com/searchresults.vi.html?ss=TP.+H%C3%B4%CC%80+Chi%CC%81+Minh%2C+Vi%C3%AA%CC%A3t+Nam&efdco=1&label=gen173nr-1BCAEoggI46AdIM1gEaPQBiAEBmAEquAEXyAEM2AEB6AEBiAIBqAIDuAL1lMaoBsACAdICJGM1MWM1ODQyLWYzMmMtNGExMi1iMWFmLWM4YzliMDE0MzJlMNgCBeACAQ&sid=a3cf4761bc87283185953cebac7c42a2&aid=304142&lang=vi&sb=1&src_elem=sb&src=index&dest_id=-3730078&dest_type=city&checkin=2024-01-02&checkout=2024-01-03&group_adults=2&no_rooms=1&group_children=0&sb_travel_purpose=leisure&selected_currency=VND&offset={}
[2023-10-13T00:45:21.972+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-10-13T00:45:21.975+0000] {process_utils.py:131} INFO - Sending 15 to group 135. PIDs of all processes in the group: [135]
[2023-10-13T00:45:21.976+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 135
[2023-10-13T00:45:21.977+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-13T00:45:22.033+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=135, status='terminated', exitcode=0, started='22:00:12') (135) terminated with exit code 0
